### ISSUE TITLE
API end point for return bike

### ISSUE THREAD

**Issue by ssp6** [dragorhast/server#45]
Need 1 to end end bike rental + 1 to check current rental information (current rental information also needed for sprint 1)

### Expected Send
GET - /users/me/rental/$bikeID

headers: { TapToGo-Auth- firebaseUID }
### Expected Return
```json
{
  status: success,
  data: {
      bikeID: 12 digit ID,
       rentalStartTime: new Date( ),
       costOfRentalSoFar:  number,
       rentalActive: boolean,
       pickUpPoint: string name,
      withinPickUpPointGeo: boolean,
      returnable: boolean   <--- seperate to withinPickUpPoint forward thinking for when drop off any where
      },
}
```

### Expected Send
DELETE - /users/me/rental/$bikeID

headers: { TapToGo-Auth- firebaseUID }
### Expected Return
```json
{
  status: success,
  data: {
      timeEnded: new Date ( ),
      totalCost: number
  }
}
```

**Comment by arlyon** [comment]
Moved to #41
